[workspace]
members = [
    "first_lesson",
    "second_lesson",
    "third_lesson",
    "fourth_lesson",
    "fifth_lesson",
    "sixth_lesson",
    "seventh_lesson",
    "eighth_lesson",
    "ninth_lesson",
    "tenth_lesson",
    "eleventh_lesson",
    "twelfth_lesson"
]
